# Generated by Django 3.1.2 on 2020-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='celery_task_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='result_file_url',
            field=models.URLField(default='lol.txt', max_length=255),
            preserve_default=False,
        ),
    ]
