# Generated by Django 3.1.2 on 2020-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20201109_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[("'", "Single-quote(')"), ('"', 'Double-quote(")'), (' ', 'No-quote')], default='"', max_length=1),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
