# Generated by Django 3.1.2 on 2020-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvSeparator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separator', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
