# Generated by Django 3.1.2 on 2020-10-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_csvseparator'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_separator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.csvseparator'),
            preserve_default=False,
        ),
    ]
